### ISSUE TITLE
IDA plugin loading fails

### ISSUE THREAD

**Issue by spaceone** [yegord/snowman#178]
I have the free version of IDA 7.0 and copied the latest plugins into the plugins folder.
Starting IDA shows an error message:

```
dlopen(/home/X/idafree-7.0/plugins/snowman64.so): /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/X/idafree-7.0/plugins/snowman64.so)
/home/X/idafree-7.0/plugins/snowman64.so: can't load file

dlopen(/home/X/idafree-7.0/plugins/snowman64.so): /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/X/idafree-7.0/plugins/snowman64.so)
/home/X/idafree-7.0/plugins/snowman64.so: can't load file
```

What can I do?

**Comment by yegord** [comment]
Apparently, I built snowman with a newer version of libstdc++ than you have and than IDA was built against.
I guess, I should fix it, but I will be able to do it only a week later.
In the meanwhile, upgrading libstdc++ should help.

**Comment by yegord** [comment]
On which system do you run IDA?
What does `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX` say?

**Comment by yegord** [comment]
Should be fixed in the latest build.
If not, please reopen.

**Comment by spaceone** [comment]
Oh, it seems I missed your answer. GLIBCXX_3.4.20. with the latest version it still doesn't work. I'll try to build it myself :)
